# Generated by Django 3.0.8 on 2021-02-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210220_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='created_at',
        ),
    ]
