# Generated by Django 3.0.8 on 2021-03-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210220_1914'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
